// This file is auto-generated. Do not edit directly.
// Run "npm run generate-permissions" to update.

export const PERMISSIONS = {
    BRANCHES_READ: 'branches.read',
    CATEGORIES_READ: 'categories.read',
    DEPARTMENTS_READ: 'departments.read',
    INVENTORY_ADJUST: 'inventory.adjust',
    INVENTORY_RECEIVE: 'inventory.receive',
    INVENTORY_RETURN: 'inventory.return',
    INVENTORY_TRANSFER: 'inventory.transfer',
    ITEMS_ACTIVATE: 'items.activate',
    ITEMS_CREATE: 'items.create',
    ITEMS_DEACTIVATE: 'items.deactivate',
    ITEMS_READ: 'items.read',
    ITEMS_UPDATE: 'items.update',
    JOBROLES_READ: 'jobRoles.read',
    LEDGER_READ: 'ledger.read',
    LEDGER_REVERSE: 'ledger.reverse',
    LOOKUPS_MANAGE: 'lookups.manage',
    LOOKUPS_READ: 'lookups.read',
    PERMISSIONS_READ: 'permissions.read',
    REASONCODES_READ: 'reasonCodes.read',
    REPORTS_VIEW: 'reports.view',
    REQUESTS_APPROVE: 'requests.approve',
    REQUESTS_CANCEL: 'requests.cancel',
    REQUESTS_CLONE: 'requests.clone',
    REQUESTS_CONFIRM: 'requests.confirm',
    REQUESTS_CREATE: 'requests.create',
    REQUESTS_ISSUE: 'requests.issue',
    REQUESTS_LINES_MANAGE: 'requests.lines.manage',
    REQUESTS_READ: 'requests.read',
    REQUESTS_REASSIGN: 'requests.reassign',
    REQUESTS_REJECT: 'requests.reject',
    REQUESTS_RESERVE: 'requests.reserve',
    REQUESTS_SUBMIT: 'requests.submit',
    REQUESTS_UPDATE: 'requests.update',
    RESERVATIONS_READ: 'reservations.read',
    ROLES_CREATE: 'roles.create',
    ROLES_MANAGE: 'roles.manage',
    ROLES_READ: 'roles.read',
    ROLES_UPDATE: 'roles.update',
    STOCK_READ: 'stock.read',
    STOCKTAKE_APPLY: 'stocktake.apply',
    STOCKTAKE_APPROVE: 'stocktake.approve',
    STOCKTAKE_CREATE: 'stocktake.create',
    STOCKTAKE_READ: 'stocktake.read',
    STOCKTAKE_STARTCOUNT: 'stocktake.startCount',
    STOCKTAKE_SUBMITCOUNT: 'stocktake.submitCount',
    STORELOCATIONS_READ: 'storeLocations.read',
    TEMPLATES_MANAGE: 'templates.manage',
    TEMPLATES_READ: 'templates.read',
    UNITS_READ: 'units.read',
    USERS_CREATE: 'users.create',
    USERS_READ: 'users.read',
    USERS_ROLES: 'users.roles',
    USERS_UPDATE: 'users.update',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];